name: vrchat_dart
description: This is a Dart client that interacts with the unofficial VRChat API
homepage: https://github.com/vrchatapi/vrchatapi-dart
version: 2.2.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vrchat_dart_generated: ^1.7.1
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  dio: ^4.0.0
  web_socket_channel: ^2.1.0
  json_annotation: ^4.5.0
  built_value: ^8.1.1
  collection: ^1.15.0

dev_dependencies:
  rexios_lints: ^2.0.1
  build_runner: ^2.0.6
  # TODO: Use hosted versions
  openapi_generator:
    git:
      url: https://github.com/Rexios80/openapi-generator-dart
      path: openapi-generator
      ref: e8b837e765103f74152829307cd689fe8f9ee419
  openapi_generator_annotations:
    git:
      url: https://github.com/Rexios80/openapi-generator-dart
      path: openapi-generator-annotations
      ref: e8b837e765103f74152829307cd689fe8f9ee419
  json_serializable: ^6.0.1

  # dart run import_sorter:main
  import_sorter: ^4.6.0

dependency_overrides:
  # Override for the bundled version in openapi_generator
  # TODO: Remove
  openapi_generator_annotations:
    git:
      url: https://github.com/Rexios80/openapi-generator-dart
      path: openapi-generator-annotations
      ref: e8b837e765103f74152829307cd689fe8f9ee419
