name: vrchat_dart
description: This is a Dart client that interacts with the unofficial VRChat API
homepage: https://github.com/vrchatapi/vrchatapi-dart
version: 2.2.8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vrchat_dart_generated: ^1.7.5
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  dio: ^4.0.0
  web_socket_channel: ^2.1.0
  json_annotation: ^4.7.0
  built_value: ^8.1.1
  collection: ^1.15.0

dev_dependencies:
  rexios_lints: ^4.0.0
  build_runner: ^2.0.6
  json_serializable: ^6.0.1
  yaml: ^3.1.1
