name: vrchat_dart
description: This is a Dart client that interacts with the unofficial VRChat API
homepage: https://github.com/vrchatapi/vrchatapi-dart
version: 3.5.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  vrchat_dart_generated: ^1.12.0
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.1
  dio: ^5.0.0
  web_socket_channel: ^2.4.0
  json_annotation: ^4.7.0
  dio_response_validator: ^0.2.1

dev_dependencies:
  rexios_lints: ^6.0.1
  build_runner: ^2.0.6
  json_serializable: ^6.0.1
  yaml: ^3.1.1
  fixer: ^0.1.0
