name: vrchat_dart
description: This is a Dart client that interacts with the unofficial VRChat API
homepage: https://github.com/vrchatapi/vrchatapi-dart
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  openapi_generator_annotations: ^3.3.0
  vrchat_dart_generated: ^1.5.2
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  dio: ^4.0.0
  web_socket_channel: ^2.1.0
  json_annotation: ^4.3.0
  built_value: ^8.1.1
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.0.6
  openapi_generator: ^3.3.0+1
  json_serializable: ^6.0.1
  lints: ^1.0.1