name: vrchat_dart_example
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  vrchat_dart:
    path: ../

  otp: ^3.1.3

dev_dependencies:
  rexios_lints: ^10.0.1

dependency_overrides:
  vrchat_dart_generated:
    path: ../../vrchat_dart_generated
