name: vrchat_dart_example_flutter
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  vrchat_dart:
    path: ../

  path_provider: ^2.0.11
  package_info_plus: ^4.0.0

dev_dependencies:
  rexios_lints: ^5.0.0

dependency_overrides:
  vrchat_dart_generated:
    path: ../../vrchat_dart_generated
